### ISSUE TITLE
Cant run tool, something wrong in default config

### ISSUE THREAD

**Issue by pschonmann** [pokornyIt/prometheus_data_dump#11]
./prometheus_data_dump --config.file=cfg.yml -v
ts=2024-02-20T10:51:33.274Z caller=main.go:72 level=info msg="Starting prometheus data export " version="(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"
ts=2024-02-20T10:51:33.274Z caller=main.go:78 level=info msg="show only configuration ane exit"

prometheus_export
Actual configuration:
Server:       [127.0.0.1:9090]
Data path:    [./dump]
Days back:    [2]
Sources:
              [localhost.+ (false)]
Labels:       [N/A]

./prometheus_data_dump --config.file=cfg.yml

ts=2024-02-20T10:52:01.085Z caller=main.go:72 level=info msg="Starting prometheus data export " version="(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"
ts=2024-02-20T10:52:01.085Z caller=main.go:92 level=error msg="problem with configuration" error="invalid character 's' looking for beginning of value"
Program did not start due to configuration error! 
	Error: invalid character 's' looking for beginning of value

**Comment by pokornyIt** [comment]
Hi, can you validate your cfg.yml file in any YAML validator?
for example: https://www.yamllint.com/ or https://codebeautify.org/yaml-validator

The message is clear speak: **Error: invalid character 's' looking for beginning of value**

**Comment by pschonmann** [comment]
yamllint cfg.yml 
```
cfg.yml
  1:1       warning  missing document start "---"  (document-start)
```
When added, still "almost" same error

```
./prometheus_data_dump --config.file=cfg.yml
ts=2024-02-20T13:25:07.561Z caller=main.go:72 level=info msg="Starting prometheus data export " version="(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"
ts=2024-02-20T13:25:07.561Z caller=main.go:92 level=error msg="problem with configuration" error="invalid character '-' in numeric literal"
Program did not start due to configuration error! 
	Error: invalid character '-' in numeric literal
```

**Comment by pokornyIt** [comment]
Please, can you share your cfg.yml? Use a private message. Ups, not supported. Attach file here.

**Comment by pschonmann** [comment]
It just cfg from relase file https://github.com/pokornyIt/prometheus_data_dump/releases/download/v1.3.0/prometheus_data_dump-v1.3.0-linux-amd64.tar.gz where server modified to 127.0.0.1

![image](https://github.com/pokornyIt/prometheus_data_dump/assets/6333844/08818b6d-7236-4df2-97d9-0462255f959d)

**Comment by pokornyIt** [comment]
Look better to your file it's tarts with `---` (three dashes). Delete the line or start it with `#`

Try this config:
```yaml
server: localhost
path: ./dump
from: 2024-02-20 00:00
to: 2024-02-20 23:59
step: 10
storeDirect: true
sources:
 - instance: localhost.+
```

**Second:** Do you have enabled API in Prometheus? Start the Prometheus service with `--web.enable-admin-api` and `--log.level=debug` parameters.

**Comment by pschonmann** [comment]
Looks promising and im getting some json out. But i want to use label to get only metrics starts with node, but still no luck. When label: section is deleted, working fine.
```
cat cfg.yml
```

```yaml
---
server: localhost
path: ./dump
from: 2024-01-19 00:00
to: 2024-01-19 01:00
step: 60
storeDirect: true
sources:
  - instance: localhost:9100 
  - instance: another_host:9100 
labels:
  - name: node

```

Getting
```
ts=2024-02-20T21:50:16.828Z caller=main.go:72 level=info msg="Starting prometheus data export " version="(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"
ts=2024-02-20T21:50:16.829Z caller=main.go:92 level=error msg="problem with configuration" error="invalid character '-' in numeric literal"
Program did not start due to configuration error! 
	Error: invalid character '-' in numeric literal
```

**Comment by pokornyIt** [comment]
I see in your configurations two errors.
1. Config starts with three dashes, it's invalid in YAML
2. labels need a second parameter `value`

Example:
```yaml
server: localhost
path: ./dump
from: 2024-01-19 00:00
to: 2024-01-19 01:00
step: 60
storeDirect: true
sources:
  - instance: localhost:9100 
  - instance: another_host:9100 
labels:
  - name: node
    value: '.*+'
```

**Comment by pschonmann** [comment]
Im not able run it without three dashes, because its give me error
```
ts=2024-02-21T09:24:29.675Z caller=main.go:72 level=info msg="Starting prometheus data export " version="(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"
ts=2024-02-21T09:24:29.675Z caller=main.go:92 level=error msg="problem with configuration" error="invalid character 's' looking for beginning of value"
Program did not start due to configuration error! 
```
And when i have this yaml and even if it valid, i have error
```
---
server: localhost
path: ./dump
from: 2024-01-19 00:00
to: 2024-01-19 01:00
step: 60
storeDirect: true
sources:
  - instance: localhost:9100 
  - instance: another_host:9100 
labels:
  - name: node
    value: '.*+'
```

error
```
ts=2024-02-21T09:31:25.140Z caller=main.go:72 level=info msg="Starting prometheus data export " version="(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"
ts=2024-02-21T09:31:25.140Z caller=main.go:92 level=error msg="problem with configuration" error="invalid character '-' in numeric literal"
Program did not start due to configuration error! 
	Error: invalid character '-' in numeric literal
```
without labels section it just works :)

./prometheus_data_dump --log.level=debug --log.format=json

```yaml
{"caller":"main.go:72","level":"info","msg":"Starting prometheus data export ","ts":"2024-02-21T09:34:35.769Z","version":"(version=v1.3.0, branch=refs/tags/v1.3.0, revision=ab5c941626702ab6ce53234f8253f77cb9766c31)"}
{"caller":"main.go:98","level":"info","msg":"start collect necessary data","ts":"2024-02-21T09:34:35.769Z"}
{"caller":"main.go:113","level":"info","msg":"requried time split to 1 time ranges","ts":"2024-02-21T09:34:35.770Z"}
{"caller":"api-reader.go:28","level":"debug","msg":"entry collect series data for instance localhost:9100","ts":"2024-02-21T09:34:35.770Z"}
{"caller":"api-reader.go:33","level":"debug","msg":"instance filter: {instance=~\"localhost:9100\"}","ts":"2024-02-21T09:34:35.770Z"}
{"caller":"api-reader.go:53","level":"debug","msg":"collect 0 from 0 series for instance localhost:9100","ts":"2024-02-21T09:34:35.778Z"}
{"caller":"storage.go:42","level":"debug","msg":"final main store path /data/petr/prometheus_export_data/dump","ts":"2024-02-21T09:34:35.778Z"}
{"caller":"storage.go:58","level":"debug","msg":"directory for store final data exist and accessible","path":"/data/petr/prometheus_export_data/dump/localhost9100","ts":"2024-02-21T09:34:35.779Z"}
{"caller":"storage.go:97","file":"organize-localhost9100.json","level":"debug","msg":"data successful saved to disk","ts":"2024-02-21T09:34:35.779Z"}
{"caller":"api-reader.go:28","level":"debug","msg":"entry collect series data for instance another_host:9100","ts":"2024-02-21T09:34:35.779Z"}
{"caller":"api-reader.go:33","level":"debug","msg":"instance filter: {instance=~\"another_host:9100\"}","ts":"2024-02-21T09:34:35.779Z"}
{"caller":"api-reader.go:53","level":"debug","msg":"collect 0 from 0 series for instance another_host:9100","ts":"2024-02-21T09:34:35.779Z"}
{"caller":"storage.go:42","level":"debug","msg":"final main store path /data/petr/prometheus_export_data/dump","ts":"2024-02-21T09:34:35.779Z"}
{"caller":"storage.go:58","level":"debug","msg":"directory for store final data exist and accessible","path":"/data/petr/prometheus_export_data/dump/another_host9100","ts":"2024-02-21T09:34:35.780Z"}
{"caller":"storage.go:97","file":"organize-another_host9100.json","level":"debug","msg":"data successful saved to disk","ts":"2024-02-21T09:34:35.780Z"}
{"caller":"main.go:163","level":"info","msg":"prepared GO coroutines channel data","ts":"2024-02-21T09:34:35.780Z"}
{"caller":"main.go:175","level":"info","msg":"wait to finish all 9 routines","ts":"2024-02-21T09:34:35.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 7","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 1","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 0","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 2","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 6","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 3","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 8","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 5","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:211","level":"debug","msg":"funish coroutine 4","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:177","level":"info","msg":"all coroutines finish 1.000537309s","ts":"2024-02-21T09:34:36.780Z"}
{"caller":"main.go:125","level":"info","msg":"program successful ends after 1.010831089s","ts":"2024-02-21T09:34:36.780Z"}

```

**Comment by pokornyIt** [comment]
It's strange. In every config.yaml dump, I see that it starts with dashes. What system do you use? What editor do you use?

```yaml
server: builder03.vrane.pokornyit.cz
path: ./dump
from: "2024-02-21 12:00"
to: "2024-02-21 13:00"
step: 10
sources:
  - instance: 'local.+'
labels:
  - label: group
    value: pc
    excludeMetrics: ^go_.*
```

You can look to your Prometheus UI and validate labels (i.e. here is define group=pc)

![image](https://github.com/pokornyIt/prometheus_data_dump/assets/8665714/1b7d676c-600b-4f9b-acdf-0c5ca2cfc13c)
